const RESIDUOS = [
	{ nome: "Jornal velho", categoria: "PAPEL", explicacao: "Papel limpo e seco vai para a coleta de papel." },
	{ nome: "Caixa de papelão", categoria: "PAPEL", explicacao: "Papelão é reciclável, mas precisa estar desmontado e seco." },
	{ nome: "Caderno usado", categoria: "PAPEL", explicacao: "As folhas são recicláveis; só o espiral de metal deve ser separado." },
	{ nome: "Revista", categoria: "PAPEL", explicacao: "Mesmo com papel brilhante, a revista entra na coleta de papel." },
	{ nome: "Envelope de papel", categoria: "PAPEL", explicacao: "Envelopes comuns são papel; os plastificados não." },
	{ nome: "Garrafa PET", categoria: "PLASTICO", explicacao: "É plástico PET, um dos materiais mais reciclados do país." },
	{ nome: "Sacola de mercado", categoria: "PLASTICO", explicacao: "Sacolas são plástico e podem ser recicladas se estiverem limpas." },
	{ nome: "Pote de margarina", categoria: "PLASTICO", explicacao: "Lave antes de descartar: restos de gordura contaminam o material." },
	{ nome: "Tampa de garrafa", categoria: "PLASTICO", explicacao: "A tampa é de um plástico diferente da garrafa, mas também é reciclável." },
	{ nome: "Canudo plástico", categoria: "PLASTICO", explicacao: "É plástico, embora o tamanho pequeno dificulte a triagem." },
	{ nome: "Garrafa de vidro", categoria: "VIDRO", explicacao: "O vidro pode ser reciclado infinitas vezes sem perder qualidade." },
	{ nome: "Pote de conserva", categoria: "VIDRO", explicacao: "Retire a tampa de metal e descarte cada material separado." },
	{ nome: "Copo de vidro", categoria: "VIDRO", explicacao: "Copos comuns vão no vidro; se estiver quebrado, embale em jornal." },
	{ nome: "Frasco de perfume", categoria: "VIDRO", explicacao: "O frasco é vidro reciclável depois de esvaziado." },
	{ nome: "Garrafa de azeite", categoria: "VIDRO", explicacao: "Enxágue antes: o óleo atrapalha a reciclagem do vidro." },
	{ nome: "Lata de refrigerante", categoria: "METAL", explicacao: "O alumínio é reciclável quantas vezes for preciso." },
	{ nome: "Lata de milho", categoria: "METAL", explicacao: "É aço, reciclável depois de lavada." },
	{ nome: "Tampa de metal", categoria: "METAL", explicacao: "Tampas metálicas vão junto com as latas." },
	{ nome: "Talher velho", categoria: "METAL", explicacao: "Talheres de inox são sucata metálica e podem ser reciclados." },
	{ nome: "Papel-alumínio limpo", categoria: "METAL", explicacao: "Apesar do nome, é metal. Só serve se estiver sem restos de comida." },
	{ nome: "Casca de banana", categoria: "ORGANICO", explicacao: "Restos de fruta viram adubo na compostagem." },
	{ nome: "Borra de café", categoria: "ORGANICO", explicacao: "A borra é ótima para compostagem e para adubar plantas." },
	{ nome: "Casca de ovo", categoria: "ORGANICO", explicacao: "Casca de ovo é orgânica e enriquece o composto com cálcio." },
	{ nome: "Folhas secas", categoria: "ORGANICO", explicacao: "Restos de poda e folhas entram na compostagem." },
	{ nome: "Guardanapo usado", categoria: "ORGANICO", explicacao: "Parece papel, mas sujo de comida ele não é mais reciclável." },
	{ nome: "Pilha AA", categoria: "ELETRONICO", explicacao: "Pilhas têm metais pesados e precisam ir a um ponto de coleta." },
	{ nome: "Bateria de celular", categoria: "ELETRONICO", explicacao: "Baterias podem vazar e contaminar o solo. Nunca no lixo comum." },
	{ nome: "Cabo USB", categoria: "ELETRONICO", explicacao: "Cabos e carregadores são lixo eletrônico." },
	{ nome: "Celular antigo", categoria: "ELETRONICO", explicacao: "Aparelhos velhos devem voltar ao fabricante ou a um ponto de coleta." },
	{ nome: "Lâmpada fluorescente", categoria: "ELETRONICO", explicacao: "Contém mercúrio e exige descarte em local específico." }
];